core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    # path('under_construction/', under_construction, name='under_construction'),
    path('', homepage, name="home"),
    path('about/', about, name="about"),
    path('services/', services, name="services"),
    path('blog/', blog, name="blog"),
    path('contact/', contact, name="contact"),
    path('courier/', Index, name="courier"),
    path('courier/<str:pk>/courier_detail', CourierInfo, name="courier_detail"),

    path('get_services/', load_services, name="load_services"),
    path('get_posts/', get_posts, name="get_posts"),
    path('request_quote/', request_a_quote, name="request_quote"),

    path('blog_detail/<int:pk>', blog_details, name='blog_detail'),
]

sifex/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('sifex/', include('sifex_system.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sifex_system/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _

# Constants for choices
COURIER_STATUS_CHOICES = (
    ("ACCEPTED", "accepted"),
    ("LOADED", "loaded"),
    ("MANIFATED", "manifested"),
    ("RCS - recieved from shipper", "RCS recieved from shipper"),
    ("OFFLOADED", "offloaded"),
    ("DEPARTED", "departed"),
    ("ON TRANSIT", "on transit"),
    ("ARRIVED", "arrived"),
    ("UNDER CLEARANCE", "under clearance"),
    ("DELIVERED", "delivered"),
)

TYPE_CHOICES = (
    ("CAN - Guanzhou", "CAN - Guanzhou"),
    ("HKG - HongKong", "HKG - HongKong"),
    ("DXB - Dubai", "DXB - Dubai"),
    ("CAN - Express", "CAN - Express"),
    ("MCO - Express", "MCO - Express"),
)

STATION_CHOICES = (
    ('CAN - Guanzhou', 'CAN - Guanzhou'),
    ('HKG - HongKong', 'HKG - HongKong'),
    ('DAR - Dar es salaam', 'DAR - Dar es salaam'),
    ('DXB - Dubai', 'DXB - Dubai'),
    ('NBO - Nairobi', 'NBO - Nairobi'),
    ('SHJ - Sharjah', 'SHJ - Sharjah'),
    ('JNB - Johanesburg', 'JNB - Johanesburg'),
    ('MCT - Muscat', 'MCT - Muscat'),
    ('BOM - Mumbai', 'BOM - Mumbai'),
    ('ADD - Addis Ababa', 'ADD - Addis Ababa'),
    ('ZNZ - Zanzibar', 'ZNZ - Zanzibar'),
    
)



class ActivityLog(models.Model):
    # Constants for activity types
    ACTIVITY_TYPES = (
        ('CREATE', 'Create'),
        ('READ', 'Read'),
        ('UPDATE', 'Update'),
        ('DELETE', 'Delete'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=10, choices=ACTIVITY_TYPES)
    description = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} {self.description} at {self.timestamp}'

class Masterawb(models.Model):
    PAYMENT_MODE = (
        ('PP', 'pp'),
        ('CC', 'cc'),
    )
    awb = models.CharField(max_length=255, blank=True)
    order_number = models.CharField(max_length=255, null=True, blank=True)
    sender_name = models.CharField(max_length=255, blank=True)
    sender_address = models.CharField(max_length=255, blank=True)
    sender_company = models.CharField(max_length=255, blank=True)
    sender_tel = models.CharField(max_length=255, blank=True)
    sender_city = models.CharField(max_length=255, blank=True)
    sender_country = models.CharField(max_length=255, blank=True)
    receiver_name = models.CharField(max_length=255, blank=True)
    receiver_address = models.CharField(max_length=255, blank=True)
    receiver_company = models.CharField(max_length=255, blank=True)
    receiver_tel = models.CharField(max_length=255, blank=True)
    receiver_city = models.CharField(max_length=255, blank=True)
    receiver_country = models.CharField(max_length=255, blank=True)
    desc = models.CharField(max_length=255, blank=True)
    freight = models.CharField(max_length=255, blank=True)
    freight_rate = models.CharField(max_length=255, blank=True)
    insurance = models.CharField(max_length=255, blank=True)
    awb_pcs = models.CharField(max_length=255, blank=True)
    awb_kg = models.FloatField(blank=True)
    arr_pcs = models.CharField(max_length=255, null=True, blank=True)
    number_of_parcel = models.CharField(max_length=255, null=True, blank=True)
    parcel_kg = models.FloatField(null=True, blank=True)
    number = models.CharField(max_length=255, null=True, blank=True)
    arr_kg = models.FloatField(null=True, blank=True)
    chargable_weight = models.CharField(max_length=255, null=True, blank=True)
    terms = models.CharField(max_length=255, null=True, blank=True)
    currency = models.CharField(max_length=255, blank=True)
    expected_arrival_date = models.DateTimeField(null=True, blank=True)
    date_received = models.DateTimeField(null=True, blank=True)
    custom_value = models.CharField(max_length=255, blank=True)
    payment_mode = models.CharField(max_length=255, null=True)
    awb_type = models.CharField(max_length=255, choices=TYPE_CHOICES, null=True)
    dlv_pcs = models.CharField(max_length=255, null=True, blank=True)
    dlv_kg = models.FloatField(null=True, blank=True)
    volume = models.CharField(max_length=255, null=True, blank=True)
    height = models.CharField(max_length=255, null=True, blank=True)
    width = models.CharField(max_length=255, null=True, blank=True)
    length = models.CharField(max_length=255, null=True, blank=True)
    accepted = models.BooleanField(default=True)
    loaded = models.BooleanField(default=False)
    manifested = models.BooleanField(default=False)
    departed = models.BooleanField(default=False)
    arrived = models.BooleanField(default=False)
    under_clearance = models.BooleanField(default=False)
    released = models.BooleanField(default=False)
    bill = models.BooleanField(default=False)
    invoice_generated = models.BooleanField(default=False)
    billed = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    POD = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='issuers')

    def __str__(self):
        return f'{self.receiver_name} {self.awb}'



class AwbLocation(models.Model):
    awb = models.ForeignKey(Masterawb, on_delete=models.CASCADE, null=True, blank=True, related_name="awb_locations")
    rack = models.CharField(max_length=255, null=True, blank=True)
    bay = models.CharField(max_length=255, null=True, blank=True)
    pcs = models.CharField(max_length=255, null=True, blank=True)



class Slaveawb(models.Model):
    PAYMENT_MODE = (
        ('PP', 'pp'),
        ('CC', 'cc'),
    )
    master = models.ForeignKey(Masterawb, on_delete=models.CASCADE, null=True, blank=True, related_name="slave_master")
    master_awb = models.CharField(max_length=255, null=True)
    awb = models.CharField(max_length=255, null=True)
    order_number = models.CharField(max_length=255, null=True)
    desc = models.CharField(max_length=255, null=True)
    freight = models.CharField(max_length=255, null=True)
    insurance = models.CharField(max_length=255, null=True)
    awb_pcs = models.CharField(max_length=255, null=True)
    awb_kg = models.FloatField(null=True)
    arr_pcs = models.CharField(max_length=255, null=True, blank=True)
    arr_kg = models.FloatField(null=True, blank=True)
    chargable_weight = models.CharField(max_length=255, null=True, blank=True)
    terms = models.CharField(max_length=255, null=True, blank=True)
    currency = models.CharField(max_length=255, null=True)
    expected_arrival_date = models.DateField(null=True, blank=True)
    number = models.CharField(max_length=255, null=True, blank=True)
    date_received = models.DateTimeField(null=True, blank=True)
    custom_value = models.CharField(max_length=255, null=True)
    payment_mode = models.CharField(max_length=255, null=True, choices=PAYMENT_MODE)
    awb_type = models.CharField(max_length=255, choices=TYPE_CHOICES, null=True)
    dlv_pcs = models.CharField(max_length=255, null=True, blank=True)
    dlv_kg = models.FloatField(null=True, blank=True)
    volume = models.CharField(max_length=255, null=True, blank=True)
    height = models.CharField(max_length=255, null=True, blank=True)
    width = models.CharField(max_length=255, null=True, blank=True)
    length = models.CharField(max_length=255, null=True, blank=True)
    accepted = models.BooleanField(default=True)
    loaded = models.BooleanField(default=False)
    manifested = models.BooleanField(default=False)
    departed = models.BooleanField(default=False)
    arrived = models.BooleanField(default=False)
    under_clearance = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    released = models.BooleanField(default=False)
    POD = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='slave_issuers')

    def __str__(self):
        return self.desc


class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.EmailField(null=True, blank=True)
    customer_phone = models.CharField(max_length=100, null=True)
    billing_address = models.TextField(null=True, blank=True)
    awb = models.ForeignKey(Masterawb, null=True, on_delete=models.CASCADE)
    origin = models.CharField(max_length=100, null=True)
    date = models.DateField()
    date_of_payment = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    total_amount_tzs = models.DecimalField(max_digits=25, decimal_places=2, blank=True, null=True)
    total_amount_usd = models.DecimalField(max_digits=25, decimal_places=2, blank=True, null=True)
    status = models.CharField(max_length=20, default='unpaid')
    invoice_detail = models.CharField(max_length=20, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='issuer_invoices')
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status
    
    class Meta:
        ordering = ['-date']  # Order by date descending (latest first)


class LineItem(models.Model):
    customer = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="invoces_line")
    tracking_key = models.CharField(max_length=255, blank=True)
    service = models.TextField(null=True)
    description = models.TextField()
    quantity = models.IntegerField()
    chargable_weight = models.FloatField(null=True)
    awb_kg = models.FloatField(null=True)
    rate = models.DecimalField(max_digits=20, decimal_places=2)
    amount_tz = models.DecimalField(max_digits=20, decimal_places=2, null=True)

templates/invoice/invoice-create.html
{% extends 'system/app/index.html' %}
{% block page %}invoice create{% endblock page %}
{% block title %}invoice create{% endblock %}
{% load static %}{% load bulma_tags %}
{% block content %}
<br>
<section class="">
    <div class="container">
        <div class="card white-ter">
            <div class="hero-body card-body">
                <form class="" method="POST" action="">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 col-lg-6 col-sm-6">
                            <label for="id_customer">Customer</label>
                            <input class="form-control" type="text" value="{{awb.receiver_name}}" name="customer" id="id_customer" required>
                        </div>
                        <div class="col-md-6 col-lg-6 col-sm-6">
                            <label for="id_customer_phone">Customer Phone</label>
                            <input class="form-control" type="text" value="{{awb.receiver_tel}}" name="customer_phone" id="id_customer_phone" required>
                        </div>
                    </div>
                    <div class="columns is-centered">
                        <div class="column is-one-third">
                            <label for="id_billing_address">Billing Address</label>
                            <input class="form-control" type="text" value="{{awb.receiver_city}}" name="billing_address" id="id_billing_address" required>
                        </div>
                        <div class="column is-one-third">
                            <label for="id_date">Date</label>
                            <input class="form-control input" type="text" name="date" id="id_date" required>
                        </div>
                        <div class="column is-one-third">
                            <label for="id_due_date">Due Date</label>
                            <input class="form-control input" type="text" name="due_date" id="id_due_date" required>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table is-fullwidth is-bordered is-hoverable is-striped datanew">
                            <thead>
                                <tr>
                                    <th>Product/Service</th>
                                    <th>Description</th>
                                    <th>Origin</th>
                                    <th>QTY</th>
                                    <th>WEIGHT</th>
                                    <th>RATE</th>
                                    <th>AMOUNT$</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><input type="text" name="service" value="{{awb.awb}}" placeholder="service" class="form-control input" required></td>
                                    <td><input type="text" name="description" value="{{awb.desc}}" placeholder="Description" class="form-control input" required></td>
                                    <td><input type="text" name="origin" value="{{awb.awb_type}}" placeholder="Origin" class="form-control input" required></td>
                                    <td><input type="text" name="quantity" value="{{awb.awb_pcs}}" placeholder="QTY" class="form-control input" required></td>
                                    <td><input type="text" name="chargable_weight" value="{{awb.chargable_weight}}" placeholder="Weight" class="form-control input chargable-weight" required></td>
                                    <td><input type="text" name="rate" value="" placeholder="Rate" class="form-control input rate" required></td>
                                    <td class="amount"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                   <div class="row">
                        <div class="col-md-4 col-lg-4">
                            <h3 class="title is-4">Total($): <span id="total"></span></h3>
                        </div>
                        <div class="col-md-8 col-lg-8">
                            <button type="submit" class="button btn btn-success btn-block is-info is-half" id="generate-btn">Generate invoice</button>
                            <button type="button" class="button btn btn-primary btn-block is-loading is-half d-none" id="loader-btn" disabled>Loading...</button>
                        </div>
                   </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block script %}
<!-- Include Flatpickr CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<!-- Include Flatpickr JS -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr("#id_date", {
            dateFormat: "Y-m-d",
            allowInput: true
        });
        flatpickr("#id_due_date", {
            dateFormat: "Y-m-d",
            allowInput: true
        });
    });

    $('table input').on("input", function () {
        var total = []
        var $tr = $(this).closest('tr');
        var rate = $("input.rate", $tr).val();
        var chargableWeight = $('input.chargable-weight', $tr).val();
        var amt = rate * chargableWeight;
        $('.amount', $tr).html(amt);
        calc_total();
    });

    function calc_total() {
        var sum = 0;
        $(".amount").each(function () {
            sum += parseFloat($(this).text());
        });
        $('#total').text(sum);
    }

    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function () {
            var name = $(this).attr('name');
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({ 'name': name, 'id': id }).val('').removeAttr('checked');
            }
        });
        newElement.find('label').each(function () {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({ 'for': forValue });
            }
        });
        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);
        return false;
    }

    function deleteForm(prefix, btn) {
        var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (total > 1) {
            btn.closest('.form-row').remove();
            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function () {
                    updateElementIndex(this, prefix, i);
                });
            }
        }
        return false;
    }

    $(document).on('click', '.add-form-row', function (e) {
        e.preventDefault();
        cloneMore('table tr:last', 'form');
        return false;
    });

    $(document).on('click', '.remove-form-row', function (e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });

    // Add loader button functionality
    document.getElementById('generate-btn').addEventListener('click', function() {
        document.getElementById('generate-btn').classList.add('d-none');
        document.getElementById('loader-btn').classList.remove('d-none');
    });
</script>
{% endblock %}

templates/invoice/invoice-hifadhi.html
{% extends 'system/app/index.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Customers list{% endblock %}

{% block page %}Customers list{% endblock page %}
{% block slogan %}list of Customers{% endblock slogan %} 

{% block style %}
    <style>
        .hide-accept-form {
            display: none;
        }
        .hide-response-form {
            display: none;
        }
        .hide-add-form {
            display: none;
        }
    </style>
{% endblock %}
{% block content %}
<div class="page-header">
    <div class="page-title">

    </div>
</div>

<div class="card">
    <div class="card-body">
    <div class="table-top">
    <div class="search-set">
    <div class="search-path">
  
    </div>
    <div class="search-input">
    <a class="btn btn-searchset"><img src="{% static 'system/assets/img/icons/search-white.svg' %}" alt="img"></a>
    </div>
        {% include 'system/partials/_messages.html' %}
    </div>
    <div class="wordset">'
    <ul>
    <li>
    <a data-bs-toggle="tooltip" data-bs-placement="top" title="pdf"><img src="{% static 'system/assets/img/icons/pdf.svg' %}" alt="img"></a>
    </li>
    <li>
    <a data-bs-toggle="tooltip" data-bs-placement="top" title="excel"><img src="{% static 'system/assets/img/icons/excel.svg' %}" alt="img"></a>
    </li>
    <li>
    <a data-bs-toggle="tooltip" data-bs-placement="top" title="print"><img src="{% static 'system/assets/img/icons/printer.svg' %}" alt="img"></a>
    </li>
    </ul>
    </div>
    </div>
    
    <div class="card mb-0" id="filter_inputs">
    <div class="card-body pb-0">

    </div>
    </div>
    
    <div class="table-responsive">
        <table class="table  datanew">
        <thead>
        <tr>
        <th>
        <label class="checkboxs">
        <input type="checkbox" id="select-all">
        <span class="checkmarks"></span>
        </label>
        </th>
        <th>Customer</th>
        <th>Product/Service</th>
        <th>Exchange Rate </th>
        <th>QTY</th>
        <th>Weight</th>
        <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for pc in pcs %}
        <tr>
        <td>
        <label class="checkboxs">
        <input type="checkbox" name="awb_id[]" value="{{pc.id}}" id="checkbox" class="loaded_status">
        <span class="checkmarks"></span>
        </label>
        </td>
        
        <td>
            <a href="">{{pc.receiver_name}}</a>
        </td>
        <td>
            <a href="">{{pc.awb}}</a>
        </td>
        {% for ex_rate in exchange_rate %}
        <td>{{ex_rate.exchange_rate}}</td>
        {% endfor %}
        <td>{{pc.awb_pcs}}</td>
        <td>{{pc.awb_kg}}</td>
        <td>
        <a class="btn btn-success" href="{% url 'invoice-create' pc.id %}" style="color: #fff;">Generate invoice</a>
        </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
{% endblock %}

templates/invoice/invoice_detail.html
{% extends 'system/app/index.html' %}
{% block page %}Invoice Detail{% endblock page %}
{% block title %}Invoice Detail{% endblock %}
{% load static %}{% load bulma_tags %}
{% block content %}
<br>
<section class="">
    <div class="container">
        <div class="card white-ter">
            <div class="hero-body card-body">
                <div class="columns is-centered">
                    <div class="column is-half">
                        <h1 class="title">Invoice Detail  No: #{{ invoice.id }} for {{ invoice.customer }}</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-lg-4 col-sm-4">
                        <label for="id_customer_phone">Customer Phone</label>
                        <input class="form-control" type="text" readonly value="{{ invoice.customer_email }}" id="id_customer_phone">
                    </div>

                    <div class="col-md-4 col-lg-4 col-sm-4">
                        <label for="id_billing_address">Billing Address</label>
                        <input class="form-control" type="text" readonly value="{{ invoice.billing_address }}" id="id_billing_address">
                    </div>

                    <div class="col-md-4 col-lg-4 col-sm-4">
                        <label for="id_billing_address">Customer Phone</label>
                        <input class="form-control" type="text" readonly value="{{ invoice.customer_phone }}" id="id_customer_phone">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-lg-3 col-sm-3">
                        <label for="id_date">Date</label>
                        <input class="form-control input" type="text" readonly value="{{ invoice.date }}" id="">
                    </div>
                    <div class="col-md-3 col-lg-3 col-sm-3">
                        <label for="id_due_date">Due Date</label>
                        <input class="form-control input" type="text" readonly value="{{ invoice.due_date }}" id="">
                    </div>

                    <div class="col-md-3 col-lg-3 col-sm-3">
                        <label for="id_due_date">Invoice Status</label>
                        <input class="form-control input" type="text" readonly value="{{ invoice.get_status }}" id="id_status">
                    </div>

                    <div class="col-md-3 col-lg-3 col-sm-3">
                        <label for="id_due_date">Payment Method</label>
                        <input class="form-control input" type="text" readonly value="{{ invoice.invoice_detail }}" id="id_detail">
                    </div>
                </div>
                
                <h2 class="subtitle">Other Details</h2>
                <div class="table-responsive">
                    <table class="table is-fullwidth is-bordered is-hoverable is-striped datanew">
                        <thead>
                            <tr>
                                <th>Service</th>
                                <th>Description</th>
                                <th>Origin</th>
                                <th>QTY</th>
                                <th>Weight</th>
                                <th>Rate</th>
                                <th>Amount (TZS)</th>
                                <th>Amount (USD)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in line_items %}
                            <tr>
                                <td>{{ item.service }}</td>
                                <td>{{ item.description }}</td>
                                <td>{{ item.customer.origin }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.chargable_weight }}</td>
                                <td>{{ item.rate }}</td>
                                <td>{{ item.amount_tz }}</td>
                                <td>{{ item.amount_usd }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="row is-centered">
                    <div class="col-md-6 col-lg-6 is-half">
                        <h3 class="title is-4">Total Amount (USD): <span>{{ invoice.total_amount_usd }}</span></h3>
                    </div>

                    <div class="col-md-6 col-lg-6 is-half">
                        <h3 class="title is-4">Total Amount (TZS): <span>{{ invoice.total_amount_tzs }}</span></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<div class="card has-background">
    <header class="card-header">
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <p class="card-header-title">
                    Change Order Status
                </p>
            </div>
            <div class="col-md-6 col-lg-6">
                <a href="{% url 'invoice_pdf' invoice.id %}" class="btn btn-secondary download-btn" download><i class="fa fa-download"></i> Download</a>
            </div>
        </div>
    </header>
    {% if invoice.get_status == 'unpaid' %}
    <div class="card-body">
        <form action="{% url 'invoice-list' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{ invoice.id }}" name="invoice_id"/>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group is-rounded">
                        <label for="invoice_status">Invoice detail</label>
                        <select class="form-control" name="status">
                            <option value="paid">Paid</option>
                            <option value="credited">Credited</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group is-rounded">
                        <label for="invoice_detail">Invoice detail</label>
                        <select class="form-control" name="invoice_detail">
                            <option value="cash">Cash</option>
                            <option value="bank">Bank</option>
                            <option value="mobile">Mobile</option>
                        </select>
                    </div>
                </div>
            </div>
        
        
        <br>

        <div class="container">
            <div class="row bt-20">
                <input class="button btn btn-secondary is-info is-rounded submit-btn" type="submit" value="Mark Payment" name="mybtn">
            </div>
        </div>

    </form>
    </div>
    {% endif %}
</div>

{% endblock %}

{% block script %}
<!-- Include Flatpickr CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<!-- Include Flatpickr JS -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        flatpickr("#id_date", {
            dateFormat: "Y-m-d",
        });
        flatpickr("#id_due_date", {
            dateFormat: "Y-m-d",
        });

        document.querySelectorAll('.download-btn').forEach(function(button) {
            button.addEventListener('click', function(e) {
                const spinner = document.createElement('span');
                spinner.className = 'spinner-border spinner-border-sm';
                spinner.role = 'status';
                spinner.ariaHidden = 'true';
                this.appendChild(spinner);
                this.classList.add('disabled');

                // Stop the loader after the download starts
                setTimeout(() => {
                    spinner.remove();
                    this.classList.remove('disabled');
                }, 2000); // Adjust the delay as necessary
            });
        });

        document.querySelectorAll('.submit-btn').forEach(function(button) {
            button.addEventListener('click', function(e) {
                const spinner = document.createElement('span');
                spinner.className = 'spinner-border spinner-border-sm';
                spinner.role = 'status';
                spinner.ariaHidden = 'true';
                this.value = 'Loading...';
                this.appendChild(spinner);
                this.classList.add('disabled');
            });
        });
    });
</script>
{% endblock %}